services:
  web:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=backend/main.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0
