[tool.black]
line-length = 200
target-version = ["py311", "py312"]
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/docs
venv/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 200 
