name: Build Develop Image and Deploy to GHCR

on:
  workflow_dispatch:
  push:
   branches:
    - main
   paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '/docs'
      - '/tests'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      
      - name: Build and Push Docker Image
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          VERSION="develop_${TIMESTAMP}"
          
          LOWERCASE_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${LOWERCASE_REPO}:${VERSION} \
            --tag ghcr.io/${LOWERCASE_REPO}:develop_latest \
            --build-arg release_version=${VERSION} \
            --push -f docker/Dockerfile .
          
